#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
"$ROOT/tests/run_m1.sh"
"$ROOT/tests/run_m2.sh"
"$ROOT/tests/run_m3.sh"
node "$ROOT/tests/run_m4.js"
"$ROOT/tests/run_m5.sh"
"$ROOT/tests/run_m6.sh"
"$ROOT/tests/run_qa_swarm.sh"

"$ROOT/tests/run_rc3_hardening.sh"
"$ROOT/tests/run_concurrency.sh"
"$ROOT/tests/run_contract_audit.sh"
"$ROOT/tests/run_ng_m1.sh"
"$ROOT/tests/run_ng_m2.sh"
"$ROOT/tests/run_stage_hardening.sh"
"$ROOT/tests/run_stdlib_1.sh"
"$ROOT/tests/run_framekit_m2.sh"
"$ROOT/tests/run_imagestats_m3.sh"

"$ROOT/tests/run_dev4_terminal_ux.sh"
"$ROOT/tests/run_observe_t0.sh"
"$ROOT/tests/run_frames.sh"
"$ROOT/tests/run_audit.sh"
"$ROOT/tests/run_mj_cli.sh"
"$ROOT/tests/run_protect.sh"
"$ROOT/tests/run_library.sh"
"$ROOT/tests/run_host.sh"
"$ROOT/tests/run_audit_queries.sh"
"$ROOT/tests/run_ui.sh"
"$ROOT/tests/run_errors.sh"
"$ROOT/tests/run_review_fixes.sh"
"$ROOT/tests/run_human_cli.sh"
"$ROOT/tests/run_c4d.sh"
"$ROOT/tests/run_c4d_guard.sh"
"$ROOT/tests/run_studio.sh"
"$ROOT/tests/run_space.sh"
"$ROOT/tests/run_qc.sh"
"$ROOT/tests/run_job_guard.sh"
"$ROOT/tests/run_aejob.sh"
"$ROOT/tests/run_hall_of_horror.sh"
"$ROOT/tests/run_install.sh"
"$ROOT/tests/run_materialized.sh"
"$ROOT/tests/run_json_quote.sh"
"$ROOT/tests/run_guides_unit.sh"
"$ROOT/tests/run_guides.sh"
"$ROOT/scripts/check-c4d-scraper-readonly.sh"
"$ROOT/scripts/check-scraper-readonly.sh"
"$ROOT/tests/run_scraper_guard.sh"

"$ROOT/tests/run_dev4_1_mac_hotfix.sh"
